version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=bms
      - MYSQL_ROOT_PASSWORD=root_pass
    ports:
      - 13306:3306
    volumes:
      - db_data:/var/lib/mysql/

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080

volumes:
  db_data: